"""Per-project context injection.

Generates a compact, project-specific context block and writes it into
{project_root}/CLAUDE.md using distinct markers. Re-injected automatically
whenever new decisions are captured for that project.

Markers used: <!-- keel:project:start --> / <!-- keel:project:end -->
(distinct from global inject.py markers to allow both to coexist)
"""

import json
import re
from datetime import datetime
from pathlib import Path
from typing import Optional

import store
import llm

PROJECTS_META_DIR = Path.home() / ".keel" / "projects"
MARKER_START      = "<!-- keel:project:start -->"
MARKER_END        = "<!-- keel:project:end -->"

PROJECT_CONTEXT_PROMPT = """You are writing a compact context block for a developer's CLAUDE.md.
It will be read by Claude Code at the start of every session in project: {project_name}

Based on these decisions (project-specific shown first, then cross-project architectural):

{decisions_text}

Write a context block with exactly these sections. Include a section only if there is
relevant content for it — skip it entirely otherwise.

## Project Decisions ({project_name})
[3-7 bullets. Format: "**Short label**: concrete choice made and why"]

## Active Constraints
[2-4 bullets: explicit rejections or tradeoffs still in place.
 ONLY include if there are decisions tagged compromise or temporary.]

## Cross-Project Principles
[2-3 bullets: architectural principles from other projects that also apply here.
 ONLY include if cross-project arch decisions exist in the input.]

RULES:
- Maximum 700 tokens total
- No preamble, no meta-commentary, no section headers for empty sections
- Each bullet encodes one concrete, actionable fact
- Write in present tense: "Uses X because Y", not "It was decided to use X"
- If fewer than 3 project-specific decisions exist, note this is early-stage and
  focus on principles that will guide the project"""


# ─────────────────────────────────────────────
# Project metadata (staleness tracking)
# ─────────────────────────────────────────────

def _project_slug(project_root: str) -> str:
    """Convert absolute path to a safe filename stem."""
    return project_root.lstrip("/").replace("/", "_")


def _meta_path(project_root: str) -> Path:
    return PROJECTS_META_DIR / f"{_project_slug(project_root)}.json"


def _load_meta(project_root: str) -> dict:
    p = _meta_path(project_root)
    if p.exists():
        try:
            return json.loads(p.read_text())
        except Exception:
            pass
    return {"last_synced_at": "", "decision_count": 0, "project": project_root}


def _save_meta(project_root: str, meta: dict) -> None:
    PROJECTS_META_DIR.mkdir(parents=True, exist_ok=True)
    _meta_path(project_root).write_text(json.dumps(meta, indent=2))


def is_stale(project_root: str) -> bool:
    """True if the project has never been synced or has new decisions since last sync."""
    if not project_root:
        return False
    meta = _load_meta(project_root)
    last_synced = meta.get("last_synced_at", "")
    if not last_synced:
        return True
    new = store.get_decisions_since(last_synced, project=project_root)
    return len(new) > 0


# ─────────────────────────────────────────────
# Decision filtering
# ─────────────────────────────────────────────

def get_relevant_decisions(project_root: str, all_decisions: Optional[list] = None) -> list:
    """Return decisions relevant to this project (capped at 30).

    Priority order:
    1. Decisions made directly in this project
    2. Cross-project decisions tagged 'arch' (global architectural principles)
    """
    if all_decisions is None:
        all_decisions = store.get_all()

    project_specific = [d for d in all_decisions if d.project == project_root]
    arch_global = [
        d for d in all_decisions
        if d.project != project_root and "arch" in json.loads(d.tags)
    ]

    seen = set()
    result = []
    for d in project_specific + arch_global:
        if d.id not in seen:
            seen.add(d.id)
            result.append(d)
        if len(result) >= 30:
            break

    return result


# ─────────────────────────────────────────────
# CLAUDE.md injection
# ─────────────────────────────────────────────

def inject_project_context(content: str, project_path: Path) -> Path:
    """Write/replace the keel project block in {project_path}/CLAUDE.md."""
    target = project_path / "CLAUDE.md"
    target.parent.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    block = (
        f"{MARKER_START}\n"
        f"<!-- auto-generated by keel · {timestamp} · do not edit this block -->\n"
        f"{content.strip()}\n"
        f"{MARKER_END}"
    )

    existing = target.read_text() if target.exists() else ""

    if MARKER_START in existing:
        updated = re.sub(
            rf"{re.escape(MARKER_START)}.*?{re.escape(MARKER_END)}",
            block,
            existing,
            flags=re.DOTALL,
        )
    else:
        updated = existing.rstrip() + ("\n\n" if existing else "") + block + "\n"

    target.write_text(updated)
    return target


def remove_project_context(project_path: Path) -> bool:
    """Remove the keel block from a project's CLAUDE.md. Returns True if removed."""
    target = project_path / "CLAUDE.md"
    if not target.exists():
        return False
    content = target.read_text()
    if MARKER_START not in content:
        return False
    cleaned = re.sub(
        rf"\n*{re.escape(MARKER_START)}.*?{re.escape(MARKER_END)}\n*",
        "\n",
        content,
        flags=re.DOTALL,
    )
    target.write_text(cleaned)
    return True


# ─────────────────────────────────────────────
# Sync
# ─────────────────────────────────────────────

def sync_project(project_root: str, verbose: bool = False) -> Optional[Path]:
    """Build and inject project context. Returns path written, or None if skipped."""
    if not project_root:
        return None

    relevant = get_relevant_decisions(project_root)
    project_name = Path(project_root).name

    if not relevant:
        if verbose:
            print(f"  No decisions for {project_name} — skipping")
        return None

    # Format decisions for the prompt
    lines = []
    for d in relevant:
        is_local = d.project == project_root
        origin = "this project" if is_local else "cross-project"
        tags = ", ".join(json.loads(d.tags)) or "none"
        lines.append(
            f"[{d.timestamp[:10]}] [{d.domain}] [{origin}] {d.title}\n"
            f"  Choice: {d.choice[:150]}\n"
            f"  Reasoning: {d.reasoning[:200]}\n"
            f"  Tags: {tags}"
        )

    if verbose:
        print(f"  Generating context for {project_name} ({len(relevant)} decisions)...")

    content = llm.complete(
        [{"role": "user", "content": PROJECT_CONTEXT_PROMPT.format(
            project_name=project_name,
            decisions_text="\n\n".join(lines),
        )}],
        max_tokens=900,
    )

    target_path = inject_project_context(content, Path(project_root))

    _save_meta(project_root, {
        "last_synced_at": datetime.utcnow().isoformat(),
        "decision_count": len(relevant),
        "project": project_root,
    })

    if verbose:
        print(f"  ✓ {project_name} → {target_path}")

    return target_path


def sync_if_stale(project_root: str, quiet: bool = False) -> Optional[Path]:
    """Sync only if the project has new decisions since last sync."""
    if is_stale(project_root):
        return sync_project(project_root, verbose=not quiet)
    return None


def sync_all(verbose: bool = False) -> dict:
    """Sync all known projects. Returns {project_root: path_written_or_None}."""
    projects = store.get_projects()
    results = {}
    for p in projects:
        root = p["project"]
        if root:
            results[root] = sync_project(root, verbose=verbose)
    return results
